### ISSUE TITLE
You need to specify which version of Node to use for this lab.

### ISSUE THREAD

**Issue by merecka** [learn-co-curriculum/react-hooks-react-app-example#11]
I attempted to run 'npm start' using the latest version of Node, Node v17.1.0, and I received an error message.  After some Google'ing I discovered that there was some incompatibilities with this version and and I had to revert back to an older version, v16.11.1, in order to get this command to execute properly.  You either need to make the newest version of Node compatible or put instructions of which version of Node to use for this lab.

Note:  I am using nvm-windows and running Windows 10 Home edition

**Comment by ihollander** [comment]
Hi @merecka - thanks for flagging this! You are correct - there is an issue with Node 17 and the version of Create React App used for our lessons that has not been fixed by the maintainers of Create React App: https://github.com/facebook/create-react-app/issues/11562

We'll update the lesson to make a note of this and clarify that students should be using Node 16. Our recommendation is to use Node 16 during your time in the program, since Node 17 is still very new and not compatible with some major JavaScript libraries.
